export default [
  {
    _id: '2',
    url: 'https://dl.dropboxusercontent.com/scl/fi/q83bcnvyyla2zavixfc5m/2-Jimmy-sized.jpg?rlkey=wecrucndun8vtj9gxcblo42l1&dl=0',
  },
  { _id: '3', url: '../../static/imgs/photo3.png' },
  { _id: '4', url: '../../static/imgs/photo4.png' },
  { _id: '9', url: '../../static/imgs/photo9.png' },
  {
    _id: '10',
    url: 'https://dl.dropboxusercontent.com/scl/fi/qmy8rex28nlhgdv1qblqo/5-red-truck-lifted-sized.jpg?rlkey=j10z4papyvkcwc5tt8vz3hyiv&dl=0',
  },
  { _id: 'dave sized',
    url:'https://dl.dropboxusercontent.com/scl/fi/m90mkgijgfiihffnqttak/6-Dave-sized.jpg?rlkey=jfd4ov320qvlwuzbh8l87xxnv&dl=0',
  },
  { _id: 'new front cleaned',
    url: 'https://dl.dropboxusercontent.com/scl/fi/o7699nrg7g69pfawlcw01/7-New-Front-cleaned-up-sized.jpg?rlkey=agnez1fuos4cnk03abpsu9rpj&dl=0',
  },
  { _id: 'guy1',
    url: 'https://dl.dropboxusercontent.com/scl/fi/mcv2sjtdxc4z7i627c9os/8-Guy-1-sized.jpg?rlkey=wusoimwz4a5n3n2q4nf6q7d22&dl=0',
  },
  { _id: 'guy2',
    url: 'https://dl.dropboxusercontent.com/scl/fi/ype1xag5txc52jngbvk3n/10-Guy-2-sized.jpg?rlkey=vuz9m9el3it1mv2h0j0h2g799&dl=0',
  },
  { _id: 'lounge2',
    url: 'https://dl.dropboxusercontent.com/scl/fi/zki5v56nkvchuk77bhdfd/11-lounge-2-sized.jpg?rlkey=9jd0us9dn537fzdg33b1iw0kq&dl=0',
  },
  { _id: 'guy3',
    url: 'https://dl.dropboxusercontent.com/scl/fi/u4fu6oq4pyyxy4y7sh8fg/12-Guy-3-sized.jpg?rlkey=a9fzx4pz1udaxrgfkls88fmkv&dl=0',
  },
  { _id: 'frontdoor',
    url: 'https://dl.dropboxusercontent.com/scl/fi/i7we05d2zjt3y3jooeytd/13-front-door-sized.jpg?rlkey=0t39sbm309hjvvt3u3jl0oyk8&dl=0',
  },
  { _id: 'guy4',
    url:'https://dl.dropboxusercontent.com/scl/fi/b1him8c3eefavdcn1hezw/14-Guy-4-sized.jpg?rlkey=dptv8ipthupj8wsby0xaxg68j&dl=0',
  },
  { _id: 'frontSized',
    url:'https://dl.dropboxusercontent.com/scl/fi/23hau5oaxf3jqnofc4qjk/Front-sized.jpg?rlkey=lv5xkmkm3ptg7vkuyhgbsqrwr&dl=0',
  },
];

