version:  2.1
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: dde3fcc4c58338dab099774f34c81bca1db56531363252d73b640bac74eb1d9b
    docker:
      - image: cimg/node:lts-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name:        Test install
          command:     'npm install'
      - run:
          name:        run all tests
          command:     |
            ./cc-test-reporter before-build
            npm test
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
      - store_artifacts:
          path:        coverage
